name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Install CMake and other dependencies
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake g++ make

      # Create a build directory and configure the project
      - name: Configure project
        run: |
          cmake -S Challenge -B build -DCMAKE_BUILD_TYPE=Release

      # Build the project
      - name: Build project
        run: |
          cmake --build build -- -j$(nproc)

      # Run the tests
      - name: Run tests
        run: |
          cd build
          ctest --output-on-failure
